few docs + adds --node-version parameter

diff --git a/install-home-nodejs b/install-home-nodejs
--- a/install-home-nodejs
+++ b/install-home-nodejs
@@ -4,8 +4,23 @@
 #
 
 STOW_VERSION="2.1.3"
-NODE_VERSION="0.6.18"
- 
+NODE_VERSION="0.7.9"
+
+for i in $*
+do
+  case $i in
+    --node-version=*)
+      NODE_VERSION=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+    ;;
+    --stow-version=*)
+      STOW_VERSION=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+    ;;
+    esac
+done
+
+# -e will block installation if compilation fails
+#set -e -x
+
 PWD=`pwd`
 
 # installation de stow
@@ -49,19 +64,20 @@ if [ ! -f ~/local/src/node-v$NODE_VERSION ]; then
 fi
 cd ~/local/src/node-v$NODE_VERSION
 ./configure --prefix=~/local/stow/node-v$NODE_VERSION
+mkdir -p ~/local/stow/node-v${NODE_VERSION}/lib/node_modules/
 make && make install
  
 # setup environnement variables for node and npm access
 grep " PATH=" ~/.profile | grep "/local/" >/dev/null
-if [ "$?" != 0 ]; then
+if [ "$?" != "0" ]; then
   echo "export PATH=\$HOME/local/bin:\${PATH:=}" >> ~/.profile
 fi
 grep " MANPATH=" ~/.profile | grep "/local/" >/dev/null
-if [ "$?" != 0 ]; then
+if [ "$?" != "0" ]; then
   echo "export MANPATH=\$HOME/local/man:\${MANPATH:=}" >> ~/.profile
 fi
 grep " LD_LIBRARY_PATH=" ~/.profile | grep "/local/" >/dev/null
-if [ "$?" != 0 ]; then
+if [ "$?" != "0" ]; then
   echo "export LD_LIBRARY_PATH=\$HOME/local/lib:\${LD_LIBRARY_PATH:=}" >> ~/.profile
 fi
 export PATH=$HOME/local/bin:${PATH:=}
@@ -70,6 +86,10 @@ export LD_LIBRARY_PATH=$HOME/local/lib:${LD_LIBRARY_PATH:=}
  
 # activate a nodejs version 
 cd ~/local/stow
+which node
+if [ "$?" == "0" ]; then
+  stow -D node-`node -v`
+fi
 stow node-v$NODE_VERSION
  
 # setup npm for internet access
